#pragma once

#include <windows.h>
#include <osg/Node>
#include <osgViewer/Viewer>
#include <osgViewer/CompositeViewer>
#include <osgDB/ReadFile>

#ifdef OSG_LIBRARY_STATIC

USE_OSGPLUGIN(ive)
USE_OSGPLUGIN(osg)
USE_OSGPLUGIN(osg2)
USE_OSGPLUGIN(rgb)
USE_OSGPLUGIN(dds)
USE_OSGPLUGIN(OpenFlight)
// USE_OSGPLUGIN(fbx)
//USE_OSGPLUGIN(png)
USE_OSGPLUGIN(tga)
//USE_OSGPLUGIN(jpeg)

USE_OSGPLUGIN(freetype)

USE_DOTOSGWRAPPER_LIBRARY(osg)
USE_DOTOSGWRAPPER_LIBRARY(osgFX)
USE_DOTOSGWRAPPER_LIBRARY(osgParticle)
//USE_DOTOSGWRAPPER_LIBRARY(osgShadow)
USE_DOTOSGWRAPPER_LIBRARY(osgSim)
USE_DOTOSGWRAPPER_LIBRARY(osgTerrain)
USE_DOTOSGWRAPPER_LIBRARY(osgText)
USE_DOTOSGWRAPPER_LIBRARY(osgViewer)
USE_DOTOSGWRAPPER_LIBRARY(osgVolume)
//USE_DOTOSGWRAPPER_LIBRARY(osgWidget)

USE_SERIALIZER_WRAPPER_LIBRARY(osg)
USE_SERIALIZER_WRAPPER_LIBRARY(osgAnimation)
USE_SERIALIZER_WRAPPER_LIBRARY(osgFX)
USE_SERIALIZER_WRAPPER_LIBRARY(osgManipulator)
USE_SERIALIZER_WRAPPER_LIBRARY(osgParticle)
//USE_SERIALIZER_WRAPPER_LIBRARY(osgShadow)
USE_SERIALIZER_WRAPPER_LIBRARY(osgSim)
USE_SERIALIZER_WRAPPER_LIBRARY(osgTerrain)
USE_SERIALIZER_WRAPPER_LIBRARY(osgText)
USE_SERIALIZER_WRAPPER_LIBRARY(osgVolume)

// include the platform specific GraphicsWindow implementation.  
USE_GRAPHICSWINDOW()

#ifdef _DEBUG

#pragma comment (lib,"ot21-OpenThreadsd.lib")
#pragma comment (lib,"osg157-osgd.lib")
#pragma comment (lib,"osg157-osgDBd.lib")
#pragma comment (lib,"osg157-osgUtild.lib")
#pragma comment (lib,"osg157-osgGAd.lib")
#pragma comment (lib,"osg157-osgViewerd.lib")
#pragma comment (lib,"osg157-osgTextd.lib")
#pragma comment (lib,"osgPlugins-3.6.2/osgdb_ived.lib")
#pragma comment (lib,"osgPlugins-3.6.2/osgdb_openflightd.lib")
#pragma comment (lib,"osgPlugins-3.6.2/osgdb_osgd.lib")
#pragma comment (lib,"osgPlugins-3.6.2/osgdb_rgbd.lib")
#pragma comment (lib,"osgPlugins-3.6.2/osgdb_deprecated_osgd.lib")
#pragma comment (lib,"osgPlugins-3.6.2/osgdb_deprecated_osgparticled.lib")
#pragma comment (lib,"osgPlugins-3.6.2/osgdb_deprecated_osganimationd.lib")
#pragma comment (lib,"osgPlugins-3.6.2/osgdb_deprecated_osgfxd.lib")
#pragma comment (lib,"osgPlugins-3.6.2/osgdb_deprecated_osgsimd.lib")
#pragma comment (lib,"osgPlugins-3.6.2/osgdb_deprecated_osgtextd.lib")
#pragma comment (lib,"osgPlugins-3.6.2/osgdb_deprecated_osgviewerd.lib")
#pragma comment (lib,"osgPlugins-3.6.2/osgdb_deprecated_osgshadowd.lib")
#pragma comment (lib,"osgPlugins-3.6.2/osgdb_deprecated_osgterraind.lib")
#pragma comment (lib,"osgPlugins-3.6.2/osgdb_deprecated_osgvolumed.lib")
//#pragma comment (lib,"osgPlugins-3.6.2/osgdb_deprecated_osgwidgetd.lib")
#pragma comment (lib,"osgPlugins-3.6.2/osgdb_serializers_osgd.lib")
#pragma comment (lib,"osgPlugins-3.6.2/osgdb_serializers_osgGAd.lib")
#pragma comment (lib,"osgPlugins-3.6.2/osgdb_serializers_osgparticled.lib")
#pragma comment (lib,"osgPlugins-3.6.2/osgdb_serializers_osgtextd.lib")
#pragma comment (lib,"osgPlugins-3.6.2/osgdb_serializers_osgterraind.lib")
#pragma comment (lib,"osgPlugins-3.6.2/osgdb_serializers_osganimationd.lib")
#pragma comment (lib,"osgPlugins-3.6.2/osgdb_serializers_osgfxd.lib")
#pragma comment (lib,"osgPlugins-3.6.2/osgdb_serializers_osgshadowd.lib")
#pragma comment (lib,"osgPlugins-3.6.2/osgdb_serializers_osgmanipulatord.lib")
#pragma comment (lib,"osgPlugins-3.6.2/osgdb_serializers_osgsimd.lib")
#pragma comment (lib,"osgPlugins-3.6.2/osgdb_serializers_osgvolumed.lib")
#pragma comment (lib,"osgPlugins-3.6.2/osgdb_freetyped.lib")
#pragma comment (lib,"osgPlugins-3.6.2/osgdb_tgad.lib")
#pragma comment (lib,"osgPlugins-3.6.2/osgdb_ddsd.lib")
#pragma comment (lib,"opengl32.lib")
//#pragma comment (lib,"osg157-osgWidgetd.lib")
#pragma comment (lib,"osg157-osgParticled.lib")
#pragma comment (lib,"osg157-osgTerraind.lib")
#pragma comment (lib,"osg157-osgAnimationd.lib")
#pragma comment (lib,"osg157-osgFXd.lib")
#pragma comment (lib,"osg157-osgShadowd.lib")
#pragma comment (lib,"osg157-osgManipulatord.lib")
#pragma comment (lib,"osg157-osgSimd.lib")
#pragma comment (lib,"osg157-osgVolumed.lib")
#pragma comment (lib,"D:/Temp/3rdParty_VS2017_v141_x64_V11_full/3rdParty_x64/x64/lib/zlibd.lib")
#pragma comment (lib,"D:/Temp/3rdParty_VS2017_v141_x64_V11_full/3rdParty_x64/x64/lib/freetype271.lib")
#pragma comment (lib,"kernel32.lib")
#pragma comment (lib,"user32.lib")
#pragma comment (lib,"gdi32.lib")
#pragma comment (lib,"winspool.lib")
#pragma comment (lib,"shell32.lib")
#pragma comment (lib,"ole32.lib")
#pragma comment (lib,"oleaut32.lib")
#pragma comment (lib,"uuid.lib")
#pragma comment (lib,"comdlg32.lib")
#pragma comment (lib,"advapi32.lib")

//#pragma comment (lib,"ws2_32.lib")
//#pragma comment (lib,"opengl32.lib")
//#pragma comment (lib,"ot20-OpenThreadsd.lib")
//#pragma comment (lib,"osg130-osgd.lib")
//#pragma comment (lib,"osg130-osgGAd.lib")
//#pragma comment (lib,"osg130-osgViewerd.lib")
//#pragma comment (lib,"osg130-osgParticled.lib")
//#pragma comment (lib,"osg130-osgDBd.lib")
//#pragma comment (lib,"osg130-osgUtild.lib")
//#pragma comment (lib,"osg130-osgManipulatord.lib")
//#pragma comment (lib,"osg130-osgTextd.lib")
//#pragma comment (lib,"osg130-osgTerraind.lib")
//#pragma comment (lib,"osg130-osgFXd.lib")
//#pragma comment (lib,"osg130-osgVolumed.lib")
//#pragma comment (lib,"osg130-osgSimd.lib")
//#pragma comment (lib,"osg130-osgAnimationd.lib")
//#pragma comment (lib,"osg130-osgWidgetd.lib")
//
//#pragma comment (lib,"lua534d.lib")
//#pragma comment (lib,"SimMathd.lib")
////#pragma comment (lib,"ShaderMasterd_s.lib")
//
//#pragma comment (lib,"osgdb_ived.lib")
//#pragma comment (lib,"osgdb_osgd.lib")
//#pragma comment (lib,"osgdb_rgbd.lib")
//#pragma comment (lib,"osgdb_OpenFlightd.lib")
//#pragma comment (lib,"osgdb_fbxd.lib")
//#pragma comment (lib,"osgdb_pngd.lib")
//#pragma comment (lib,"osgdb_tgad.lib")
//#pragma comment (lib,"osgdb_jpegd.lib")
//#pragma comment (lib,"osgdb_freetyped.lib")
//
//#pragma comment (lib,"osgdb_serializers_osgd.lib")
//#pragma comment (lib,"osgdb_serializers_osganimationd.lib")
//#pragma comment (lib,"osgdb_serializers_osgfxd.lib")
//#pragma comment (lib,"osgdb_serializers_osgmanipulatord.lib")
//#pragma comment (lib,"osgdb_serializers_osgparticled.lib")
////#pragma comment (lib,"osgdb_serializers_osgshadowd.lib")
//#pragma comment (lib,"osgdb_serializers_osgsimd.lib")
//#pragma comment (lib,"osgdb_serializers_osgterraind.lib")
//#pragma comment (lib,"osgdb_serializers_osgtextd.lib")
//#pragma comment (lib,"osgdb_serializers_osgvolumed.lib")
//
//#pragma comment (lib,"osgdb_deprecated_osgd.lib")
//#pragma comment (lib,"osgdb_deprecated_osgfxd.lib")
//#pragma comment (lib,"osgdb_deprecated_osgparticled.lib")
////#pragma comment (lib,"osgdb_deprecated_osgshadowd.lib")
//#pragma comment (lib,"osgdb_deprecated_osgsimd.lib")
//#pragma comment (lib,"osgdb_deprecated_osgterraind.lib")
//#pragma comment (lib,"osgdb_deprecated_osgtextd.lib")
//#pragma comment (lib,"osgdb_deprecated_osgviewerd.lib")
//#pragma comment (lib,"osgdb_deprecated_osgvolumed.lib")
//#pragma comment (lib,"osgdb_deprecated_osgwidgetd.lib")
//#pragma comment (lib,"osgdb_deprecated_osganimationd.lib")
//
//#pragma comment (lib,"zlibd.lib")
//#pragma comment (lib,"libpng14d.lib")
//#pragma comment (lib,"legacy_stdio_definitions.lib")
//#pragma comment (lib,"freetype242_D.lib")
//#pragma comment (lib,"libfbxsdk-md.lib")

#else

#pragma comment (lib,"Qt5Core.lib")
#pragma comment (lib,"Qt5Widgets.lib")
#pragma comment (lib,"Qt5Gui.lib")
#pragma comment (lib,"Qt5Opengl.lib")
#pragma comment (lib,"ot21-OpenThreads.lib")
#pragma comment (lib,"osg157-osg.lib")
#pragma comment (lib,"osg157-osgDB.lib")
#pragma comment (lib,"osg157-osgUtil.lib")
#pragma comment (lib,"osg157-osgGA.lib")
#pragma comment (lib,"osg157-osgViewer.lib")
#pragma comment (lib,"osg157-osgText.lib")
#pragma comment (lib,"osgPlugins-3.6.2/osgdb_ive.lib")
#pragma comment (lib,"osgPlugins-3.6.2/osgdb_openflight.lib")
#pragma comment (lib,"osgPlugins-3.6.2/osgdb_osg.lib")
#pragma comment (lib,"osgPlugins-3.6.2/osgdb_rgb.lib")
#pragma comment (lib,"osgPlugins-3.6.2/osgdb_deprecated_osg.lib")
#pragma comment (lib,"osgPlugins-3.6.2/osgdb_deprecated_osgparticle.lib")
#pragma comment (lib,"osgPlugins-3.6.2/osgdb_deprecated_osganimation.lib")
#pragma comment (lib,"osgPlugins-3.6.2/osgdb_deprecated_osgfx.lib")
#pragma comment (lib,"osgPlugins-3.6.2/osgdb_deprecated_osgsim.lib")
#pragma comment (lib,"osgPlugins-3.6.2/osgdb_deprecated_osgtext.lib")
#pragma comment (lib,"osgPlugins-3.6.2/osgdb_deprecated_osgviewer.lib")
#pragma comment (lib,"osgPlugins-3.6.2/osgdb_deprecated_osgshadow.lib")
#pragma comment (lib,"osgPlugins-3.6.2/osgdb_deprecated_osgterrain.lib")
#pragma comment (lib,"osgPlugins-3.6.2/osgdb_deprecated_osgvolume.lib")
//#pragma comment (lib,"osgPlugins-3.6.2/osgdb_deprecated_osgwidget.lib")
#pragma comment (lib,"osgPlugins-3.6.2/osgdb_serializers_osg.lib")
#pragma comment (lib,"osgPlugins-3.6.2/osgdb_serializers_osgGA.lib")
#pragma comment (lib,"osgPlugins-3.6.2/osgdb_serializers_osgparticle.lib")
#pragma comment (lib,"osgPlugins-3.6.2/osgdb_serializers_osgtext.lib")
#pragma comment (lib,"osgPlugins-3.6.2/osgdb_serializers_osgterrain.lib")
#pragma comment (lib,"osgPlugins-3.6.2/osgdb_serializers_osganimation.lib")
#pragma comment (lib,"osgPlugins-3.6.2/osgdb_serializers_osgfx.lib")
#pragma comment (lib,"osgPlugins-3.6.2/osgdb_serializers_osgshadow.lib")
#pragma comment (lib,"osgPlugins-3.6.2/osgdb_serializers_osgmanipulator.lib")
#pragma comment (lib,"osgPlugins-3.6.2/osgdb_serializers_osgsim.lib")
#pragma comment (lib,"osgPlugins-3.6.2/osgdb_serializers_osgvolume.lib")
#pragma comment (lib,"osgPlugins-3.6.2/osgdb_freetype.lib")
#pragma comment (lib,"osgPlugins-3.6.2/osgdb_tga.lib")
#pragma comment (lib,"osgPlugins-3.6.2/osgdb_dds.lib")
#pragma comment (lib,"opengl32.lib")
//#pragma comment (lib,"osg157-osgWidget.lib") 
#pragma comment (lib,"osg157-osgParticle.lib")
#pragma comment (lib,"osg157-osgTerrain.lib")
#pragma comment (lib,"osg157-osgAnimation.lib")
#pragma comment (lib,"osg157-osgFX.lib")
#pragma comment (lib,"osg157-osgShadow.lib")
#pragma comment (lib,"osg157-osgManipulator.lib")
#pragma comment (lib,"osg157-osgSim.lib")
#pragma comment (lib,"osg157-osgVolume.lib")
#pragma comment (lib,"D:/Temp/3rdParty_VS2017_v141_x64_V11_full/3rdParty_x64/x64/lib/zlib.lib")
#pragma comment (lib,"D:/Temp/3rdParty_VS2017_v141_x64_V11_full/3rdParty_x64/x64/lib/freetype271.lib")
#pragma comment (lib,"kernel32.lib")
#pragma comment (lib,"user32.lib")
#pragma comment (lib,"gdi32.lib")
#pragma comment (lib,"winspool.lib")
#pragma comment (lib,"shell32.lib")
#pragma comment (lib,"ole32.lib")
#pragma comment (lib,"oleaut32.lib")
#pragma comment (lib,"uuid.lib")
#pragma comment (lib,"comdlg32.lib")
#pragma comment (lib,"advapi32.lib")

#endif

#endif
